### ISSUE TITLE
Vertebral labeling error for sub-847751

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/dcm-metric-normalization#12]
# Description

Following the comments from Markus Hupp in the [presentation](https://docs.google.com/presentation/d/1mO2cwqrWSDA9aiov4pUzIPgA01OFOXdjDAwEqwoVjig/edit#slide=id.g22bf5f6d901_0_40)

Some subjects have mislabeled discs. 

## sub-847751
Comment: 
![image](https://user-images.githubusercontent.com/71230552/232550832-546a6ef7-ac33-4510-9f96-1901df12aa35.png)

Current labeling: 

![image](https://user-images.githubusercontent.com/71230552/232562377-50993dc3-ba74-49cf-9c89-7ec50aa97d73.png)

This should be C1/C2: 

![image](https://user-images.githubusercontent.com/71230552/232563505-b3393d5c-3996-450d-8094-e26d2daecedf.png)

**Comment by valosekj** [comment]
Fixed by https://github.com/neuropoly/data-management/issues/231 --> closing this issue
