### ISSUE TITLE
How to optimally bring sagittal labeling to axial image

### ISSUE THREAD

**Issue by valosekj** [sct-pipeline/dcm-metric-normalization#9]
## Description

Commonly, we have available two sequences with the following parameters:

- `sagittal T2w` (or `sagittal/3D T1w`): large FOV - suitable for vertebral labeling; low resolution in the axial plane - bad for morphometric analysis
- `axial T2w` or `axial T2star`: small FOV - bad for vertebral labeling; high resolution in the axial plane - suitable for morphometric analysis

Since we are interested in morphometric analysis, we need: (a) high resolution in the axial plane (`axial T2w`) as well as (b) vertebral labeling (`sagittal T2w`) to be able to compute morphometrics per level.

## Analysis pipeline

There are two possible processing pipelines:

1. [Label sagittal image](https://github.com/sct-pipeline/dcm-metric-normalization/blob/6b44e12b7a07d03a23c4590cf3559571ef7339cb/scripts/process_data_dcm-zurich.sh#L125) and [bring the labeling to `axial T2w`](https://github.com/sct-pipeline/dcm-metric-normalization/blob/6b44e12b7a07d03a23c4590cf3559571ef7339cb/scripts/process_data_dcm-zurich.sh#L145-L146)

2. [Register sagittal image to PAM50 template](https://github.com/spine-generic/spine-generic/blob/3aa69465063d823088b2c819d3ad9b81725b2fc8/process_data.sh#L159-L160) and [bring PAM50_levels.nii.gz to `axial T2w`](https://github.com/spine-generic/spine-generic/blob/3aa69465063d823088b2c819d3ad9b81725b2fc8/process_data.sh#L249-L250)

Option 1 works reasonably if there was no repositioning of the subject during scanning. Moreover, it is faster than option 2 which uses `sct_register_to_template`.

Yet, for both options, we need spinal cord segmentation of the sagittal image. In option 1 for `sct_label_vertebra`; in option 2 for `sct_register_to_template`. That's kind of annoying because it takes time to manually correct the spinal cord segmentation of the sagittal image. (Note that we are already manually correcting spinal cord segmentation of the axial image which we need for morphometrics analysis.)

If the spinal cord segmentation of the sagittal image is not perfect, the result of option 1 contains missing slices:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/39456460/225738653-999f15dc-bed2-4bc0-8090-223d9f576947.png">

This is not ideal for [`sct_process_segmentation`](https://github.com/sct-pipeline/dcm-metric-normalization/blob/6b44e12b7a07d03a23c4590cf3559571ef7339cb/scripts/process_data_dcm-zurich.sh#L153) because it then outputs empty `VertLevel` fields:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/39456460/225740625-98b91be2-d793-45de-a0e1-2fc0611dfb67.png">

I am wondering if there is a better approach we could use.

**Comment by valosekj** [comment]
Another option would be to bring only disc labels from the sagittal image to the axial image and run `sct_label_vertebrae` with axial spinal cord segmentation using sagittal discs.

This is, however, limited because `sct_label_vertebrae` doesn’t just project the disc labels on the segmentation, instead
 it uses the [straightening step](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3395) resulting in:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/39456460/225748751-9cea435a-0a3c-4927-9f43-b589df397fd0.png">

**Comment by jcohenadad** [comment]
> Another option would be to bring only disc labels from the sagittal image to the axial image and run sct_label_vertebrae with axial spinal cord segmentation using sagittal discs.

I like this idea, especially given that in the future, `sct_label_vertebrae` will _only_ label discs, and then we will project the disc labels only the cord to get the level. 

p.s. in your picture, the labelling looks a bit "off"

**Comment by valosekj** [comment]
For a summary, we use `sct_register_multimodal` and `sct_apply_transfo` to bring T2w sagittal disc labels to T2w axial space:

https://github.com/sct-pipeline/dcm-metric-normalization/blob/d985ac0ca24d6253bfe717310f4c6a3529243b60/scripts/process_data_dcm-zurich.sh#L157-L164

And `sct_label_utils` to generate labeled spinal cord segmentation:

https://github.com/sct-pipeline/dcm-metric-normalization/blob/d985ac0ca24d6253bfe717310f4c6a3529243b60/scripts/process_data_dcm-zurich.sh#L171-L174
